#ifndef PRINTEDDOCUMENTVERIFICATIONSYSTEM_ENUMTYPES_H
#define PRINTEDDOCUMENTVERIFICATIONSYSTEM_ENUMTYPES_H

namespace PDLS {

    enum class FileType {IMG, TXT, XML, PDF, CRYPTO};

    /*
     * Hash Length's
     * MD5    : 128 bit
     * SHA1   : 160 bit
     * SHA224 : 224 bit
     * SHA256 : 256 bit
     * SHA384 : 384 bit
     * SHA512 : 512 bit
     */
    enum class ContentHashType {MD5, SHA1, SHA224, SHA256, SHA384, SHA512};

    enum class ValidationState {VALID, INVALID};

    enum class SignatureVerificationState {CERT_VALID_SIG_VALID, CERT_INVALID_SIG_VALID, CERT_VALID_SIG_INVALID, CERT_INVALID_SIG_INVALID};

    enum class DocumentVerificationState {
        CONTENT_VALID_CERT_VALID_SIG_VALID,
        CONTENT_VALID_CERT_VALID_SIG_INVALID,
        CONTENT_VALID_CERT_INVALID_SIG_VALID,
        CONTENT_VALID_CERT_INVALID_SIG_INVALID,
        CONTENT_INVALID_CERT_VALID_SIG_VALID,
        CONTENT_INVALID_CERT_VALID_SIG_INVALID,
        CONTENT_INVALID_CERT_INVALID_SIG_VALID,
        CONTENT_INVALID_CERT_INVALID_SIG_INVALID
    };

}

#endif //PRINTEDDOCUMENTVERIFICATIONSYSTEM_ENUMTYPES_H
